kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhoai-access
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
