apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-agent-finance.fullname" . }}
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Release.Name }}-chatbot"}]'
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-llm-agent-finance"
    {{- include "llm-agent-finance.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "llm-agent-finance.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "llm-agent-finance.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.global.image.usePullSecret }}
      imagePullSecrets:
      - name: llm-agent-finance-pull-secret
      {{- end }}
      {{ if eq .Values.global.useServiceAccount true }}
      serviceAccountName: {{ include "llm-agent-finance.fullname" . }}
      {{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}{{ .Values.image.name }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.image.port }}
          env:
            - name: CHROMA_HOST
              value: "{{ .Release.Name }}-chromadb"
            - name: CHROMA_COLLECTION_NAME
              value: "test"
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: agentic-secret
                  key: TAVILY_API_KEY
            - name: OPENAI_API_BASE
              valueFrom:
                secretKeyRef:
                  name: agentic-secret
                  key: OPENAI_API_BASE
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: agentic-secret
                  key: OPENAI_API_KEY
            - name: OPENAI_API_MODEL
              valueFrom:
                secretKeyRef:
                  name: agentic-secret
                  key: OPENAI_API_MODEL
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: {{ .Values.image.port }}
          #     scheme: HTTP
          #   timeoutSeconds: 1
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: {{ .Values.image.port }}
          #     scheme: HTTP
          #   timeoutSeconds: 1
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          # startupProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: {{ .Values.image.port }}
          #     scheme: HTTP
          #   timeoutSeconds: 1
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
