apiVersion: v1
kind: Service
metadata:
  name: chroma-db
  labels:
    io.kompose.service: chroma-db
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    io.kompose.service: chroma-db
