apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: streamlit-app
  name: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: streamlit-app
    spec:
      serviceAccountName: streamlit-app-secrets
      containers:
        - image: quay.io/rh-ee-petdavis/llm-agent-finance-streamlit-app
          imagePullPolicy: Always
          name: streamlit-app
          envFrom:
            - secretRef:
                name: streamlit-secret
          ports:
            - containerPort: 8501
              protocol: TCP
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret-volume
              readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: streamlit-secret
      restartPolicy: Always
