apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "llm-agent-finance.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
