kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "llm-agent-finance.fullname" . }}
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-llm-agent-finance"
    {{- include "llm-agent-finance.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "llm-agent-finance.fullname" . }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: "{{ include "llm-agent-finance.fullname" . }}"
        deployment: {{ include "llm-agent-finance.fullname" . }}
        app.kubernetes.io/part-of: "{{ .Release.Name }}-llm-agent-finance"
        {{- include "llm-agent-finance.labels" . | nindent 8 }}
        {{- include "llm-agent-finance.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init-db
          image: quay.io/rh-ee-petdavis/chroma_assets
          command: 
            - /bin/sh
          args:
            - '-ec'
            - 'if [ ! -f /data/chroma.sqlite3 ]; then cp -rfv /assets/* /data/; fi'
          volumeMounts:
            - name: {{ include "llm-agent-finance.fullname" . }}
              mountPath: /data
      containers:
        - name: chromadb
          image: ghcr.io/chroma-core/chroma:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: "/data"
              name: {{ include "llm-agent-finance.fullname" . }}
          env:
#            - name: RUST_BACKTRACE
#              value: 'full'
            - name: CHROMA_PERSIST_DIRECTORY
              value: "/data"
            - name: CHROMA_COLLECTION_NAME
              value: "financial_reports"
            - name: EMBEDDING_MODEL
              value: "all-MiniLM-L6-v2"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: {{ include "llm-agent-finance.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "llm-agent-finance.fullname" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
