kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "llm-agent-finance.fullname" . }}
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-llm-agent-finance"
    {{- include "llm-agent-finance.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "llm-agent-finance.fullname" . }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: "{{ include "llm-agent-finance.fullname" . }}"
        deployment: {{ include "llm-agent-finance.fullname" . }}
        app.kubernetes.io/part-of: "{{ .Release.Name }}-llm-agent-finance"
        {{- include "llm-agent-finance.labels" . | nindent 8 }}
        {{- include "llm-agent-finance.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: chromadb
          image: "{{ .Values.global.image.repository }}{{ .Values.image.name }}:{{ .Values.global.image.tag }}"
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: "/data"
              name: {{ include "llm-agent-finance.fullname" . }}
#          env:
#            - name: RUST_BACKTRACE
#              value: 'full'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: {{ include "llm-agent-finance.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "llm-agent-finance.fullname" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
